/** @type {import('tailwindcss').Config} */
/** Palette aligned with frontendv2-nextbckp/summary.html (MD3-style command UI) */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        headline: ['Manrope', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      colors: {
        'tertiary-container': '#9d0011',
        'on-secondary': '#ffffff',
        'inverse-on-surface': '#eff1f3',
        'surface-tint': '#2b5bb5',
        'on-secondary-container': '#4e6874',
        'on-primary-fixed': '#001945',
        'surface-dim': '#d8dadc',
        'on-secondary-fixed-variant': '#304a55',
        'tertiary-fixed-dim': '#ffb3ac',
        'surface-container-high': '#e6e8ea',
        'surface-bright': '#f8f9fb',
        'error-container': '#ffdad6',
        'secondary-container': '#cbe7f5',
        'surface-container': '#eceef0',
        'on-error-container': '#93000a',
        'surface-container-highest': '#e0e3e5',
        'outline-variant': '#c3c6d4',
        'on-tertiary-fixed-variant': '#930010',
        'surface-container-low': '#f2f4f6',
        'secondary-fixed-dim': '#afcbd8',
        'on-secondary-fixed': '#021f29',
        outline: '#737783',
        'on-primary-fixed-variant': '#00429c',
        'tertiary-fixed': '#ffdad6',
        'on-error': '#ffffff',
        'primary-fixed': '#d9e2ff',
        'on-tertiary': '#ffffff',
        'on-surface-variant': '#434652',
        'on-tertiary-container': '#ffa59d',
        'on-primary-container': '#a1bbff',
        'on-background': '#191c1e',
        'surface-container-lowest': '#ffffff',
        error: '#ba1a1a',
        tertiary: '#720009',
        'primary-fixed-dim': '#b0c6ff',
        background: '#f8f9fb',
        'on-primary': '#ffffff',
        surface: '#f8f9fb',
        'primary-container': '#0d47a1',
        'on-surface': '#191c1e',
        'inverse-surface': '#2d3133',
        'surface-variant': '#e0e3e5',
        secondary: '#48626e',
        'inverse-primary': '#b0c6ff',
        'on-tertiary-fixed': '#410003',
        'secondary-fixed': '#cbe7f5',
        primary: '#003178',
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
}
