/** @type {import('tailwindcss').Config} */
/** Palette aligned with frontendv2-nextbckp/summary.html (MD3-style command UI) */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        headline: ['Manrope', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      colors: {
        panel: 'var(--ui-panel)',
        muted: 'var(--ui-muted)',
        success: 'var(--ui-success)',
        warning: 'var(--ui-warning)',
        danger: 'var(--ui-danger)',
        slate: {
          50: 'rgb(var(--ui-neutral-50) / <alpha-value>)', 100: 'rgb(var(--ui-neutral-100) / <alpha-value>)',
          200: 'rgb(var(--ui-neutral-200) / <alpha-value>)', 300: 'rgb(var(--ui-neutral-300) / <alpha-value>)',
          400: 'rgb(var(--ui-neutral-400) / <alpha-value>)', 500: 'rgb(var(--ui-neutral-500) / <alpha-value>)',
          600: 'rgb(var(--ui-neutral-600) / <alpha-value>)', 700: 'rgb(var(--ui-neutral-700) / <alpha-value>)',
          800: 'rgb(var(--ui-neutral-800) / <alpha-value>)', 900: 'rgb(var(--ui-neutral-900) / <alpha-value>)',
          950: 'rgb(var(--ui-neutral-950) / <alpha-value>)',
        },
        gray: {
          50: 'rgb(var(--ui-neutral-50) / <alpha-value>)', 100: 'rgb(var(--ui-neutral-100) / <alpha-value>)',
          200: 'rgb(var(--ui-neutral-200) / <alpha-value>)', 300: 'rgb(var(--ui-neutral-300) / <alpha-value>)',
          400: 'rgb(var(--ui-neutral-400) / <alpha-value>)', 500: 'rgb(var(--ui-neutral-500) / <alpha-value>)',
          600: 'rgb(var(--ui-neutral-600) / <alpha-value>)', 700: 'rgb(var(--ui-neutral-700) / <alpha-value>)',
          800: 'rgb(var(--ui-neutral-800) / <alpha-value>)', 900: 'rgb(var(--ui-neutral-900) / <alpha-value>)',
          950: 'rgb(var(--ui-neutral-950) / <alpha-value>)',
        },
        blue: Object.fromEntries([50,100,200,300,400,500,600,700,800,900,950].map(n => [n, 'rgb(var(--ui-accent-rgb) / <alpha-value>)'])),
        sky: Object.fromEntries([50,100,200,300,400,500,600,700,800,900,950].map(n => [n, 'rgb(var(--ui-accent-rgb) / <alpha-value>)'])),
        orange: Object.fromEntries([50,100,200,300,400,500,600,700,800,900,950].map(n => [n, 'rgb(var(--ui-accent-rgb) / <alpha-value>)'])),
        green: Object.fromEntries([50,100,200,300,400,500,600,700,800,900,950].map(n => [n, 'var(--ui-success)'])),
        emerald: Object.fromEntries([50,100,200,300,400,500,600,700,800,900,950].map(n => [n, 'var(--ui-success)'])),
        yellow: Object.fromEntries([50,100,200,300,400,500,600,700,800,900,950].map(n => [n, 'var(--ui-warning)'])),
        red: Object.fromEntries([50,100,200,300,400,500,600,700,800,900,950].map(n => [n, 'var(--ui-danger)'])),
        rose: Object.fromEntries([50,100,200,300,400,500,600,700,800,900,950].map(n => [n, 'var(--ui-danger)'])),
        purple: Object.fromEntries([50,100,200,300,400,500,600,700,800,900,950].map(n => [n, 'rgb(var(--ui-accent-rgb) / <alpha-value>)'])),
        violet: Object.fromEntries([50,100,200,300,400,500,600,700,800,900,950].map(n => [n, 'rgb(var(--ui-accent-rgb) / <alpha-value>)'])),
        'tertiary-container': 'var(--ui-danger)',
        'on-secondary': 'var(--ui-button-text)',
        'inverse-on-surface': 'var(--ui-background)',
        'surface-tint': 'var(--ui-accent)',
        'on-secondary-container': 'var(--ui-text)',
        'on-primary-fixed': 'var(--ui-button-text)',
        'surface-dim': 'var(--ui-background)',
        'on-secondary-fixed-variant': 'var(--ui-muted)',
        'tertiary-fixed-dim': 'var(--ui-danger)',
        'surface-container-high': 'var(--ui-panel)',
        'surface-bright': 'var(--ui-surface)',
        'error-container': 'var(--ui-panel)',
        'secondary-container': 'var(--ui-panel)',
        'surface-container': 'var(--ui-surface)',
        'on-error-container': 'var(--ui-danger)',
        'surface-container-highest': 'var(--ui-panel)',
        'outline-variant': 'var(--ui-border)',
        'on-tertiary-fixed-variant': 'var(--ui-danger)',
        'surface-container-low': 'var(--ui-surface)',
        'secondary-fixed-dim': 'var(--ui-border)',
        'on-secondary-fixed': 'var(--ui-text)',
        outline: 'var(--ui-border)',
        'on-primary-fixed-variant': 'var(--ui-accent)',
        'tertiary-fixed': 'var(--ui-panel)',
        'on-error': 'var(--ui-button-text)',
        'primary-fixed': 'var(--ui-panel)',
        'on-tertiary': 'var(--ui-button-text)',
        'on-surface-variant': 'var(--ui-muted)',
        'on-tertiary-container': 'var(--ui-button-text)',
        'on-primary-container': 'var(--ui-button-text)',
        'on-background': 'var(--ui-text)',
        'surface-container-lowest': 'var(--ui-panel)',
        error: 'var(--ui-danger)',
        tertiary: 'var(--ui-danger)',
        'primary-fixed-dim': 'var(--ui-border)',
        background: 'var(--ui-background)',
        'on-primary': 'var(--ui-button-text)',
        surface: 'var(--ui-background)',
        'primary-container': 'var(--ui-accent)',
        'on-surface': 'var(--ui-text)',
        'inverse-surface': 'var(--ui-text)',
        'surface-variant': 'var(--ui-panel)',
        secondary: 'var(--ui-muted)',
        'inverse-primary': 'var(--ui-background)',
        'on-tertiary-fixed': 'var(--ui-button-text)',
        'secondary-fixed': 'var(--ui-panel)',
        primary: 'var(--ui-accent)',
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
}
